-- Department Selection System - Database Schema
-- Focus: Registration Module + core supporting tables

CREATE DATABASE IF NOT EXISTS department_selection;
USE department_selection;

-- ======================
-- USERS / AUTHENTICATION
-- ======================
CREATE TABLE users (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    student_id      VARCHAR(50)  UNIQUE NOT NULL,          -- University Student ID
    email           VARCHAR(150) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            ENUM('student', 'admin') DEFAULT 'student',
    is_active       TINYINT(1)   DEFAULT 1,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_student_id (student_id),
    INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ======================
-- STUDENT PERSONAL INFO
-- ======================
CREATE TABLE student_profiles (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id             INT UNSIGNED NOT NULL,
    
    -- Personal Information
    first_name          VARCHAR(100) NOT NULL,
    middle_name         VARCHAR(100),
    last_name           VARCHAR(100) NOT NULL,
    gender              ENUM('Male', 'Female', 'Other') NOT NULL,
    date_of_birth       DATE,
    phone               VARCHAR(20),
    national_id         VARCHAR(50),
    
    -- Address
    region              VARCHAR(100),
    city                VARCHAR(100),
    address             TEXT,
    
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY uk_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ======================
-- ACADEMIC INFORMATION
-- ======================
CREATE TABLE student_academic (
    id                      INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id                 INT UNSIGNED NOT NULL,
    
    -- High School / Previous Education
    high_school_name        VARCHAR(200),
    high_school_year        YEAR,
    
    -- Scores (adjust according to your university rules)
    total_score             DECIMAL(8,2),           -- Overall entrance / calculated score
    gpa                     DECIMAL(4,2),           -- If applicable
    english_score           DECIMAL(5,2),
    mathematics_score       DECIMAL(5,2),
    science_score           DECIMAL(5,2),
    social_score            DECIMAL(5,2),
    
    -- Category / Quota (common in many universities)
    category                ENUM('Regular', 'Special Needs', 'Regional Quota', 'Other') DEFAULT 'Regular',
    
    -- Additional academic fields (can be extended)
    stream                  VARCHAR(100),           -- e.g. Natural Science, Social Science
    remarks                 TEXT,
    
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY uk_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ======================
-- ADMINS (optional separate table or use users.role)
-- ======================
-- We use the users table with role = 'admin'. 
-- You can later add admin_profiles if needed.

-- ======================
-- SAMPLE ADMIN (password: Admin@123)
-- ======================
-- Password hash for "Admin@123" will be generated by the application
-- INSERT INTO users (student_id, email, password_hash, role) 
-- VALUES ('ADMIN001', 'admin@university.edu', '$2b$10$...', 'admin');

-- ======================
-- COLLEGES / SCHOOLS
-- ======================
CREATE TABLE colleges (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(150) NOT NULL UNIQUE,
    code            VARCHAR(20)  UNIQUE,
    description     TEXT,
    is_active       TINYINT(1) DEFAULT 1,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ======================
-- DEPARTMENTS
-- ======================
CREATE TABLE departments (
    id                      INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    college_id              INT UNSIGNED NOT NULL,
    name                    VARCHAR(150) NOT NULL,
    code                    VARCHAR(20)  UNIQUE,
    description             TEXT,
    
    -- Capacity
    capacity                INT UNSIGNED NOT NULL DEFAULT 0,
    remaining_capacity      INT UNSIGNED NOT NULL DEFAULT 0,  -- Updated during assignment
    
    -- Minimum Requirements
    min_total_score         DECIMAL(8,2) DEFAULT 0,
    min_gpa                 DECIMAL(4,2) DEFAULT 0,
    min_english             DECIMAL(5,2) DEFAULT 0,
    min_mathematics         DECIMAL(5,2) DEFAULT 0,
    min_science             DECIMAL(5,2) DEFAULT 0,
    min_social              DECIMAL(5,2) DEFAULT 0,
    
    -- Stream restriction (NULL = open to all)
    allowed_stream          VARCHAR(100),           -- e.g. 'Natural Science', 'Social Science', NULL
    
    -- Priority / Ranking weight (higher = preferred in ties if needed)
    priority_order          INT DEFAULT 100,
    
    is_active               TINYINT(1) DEFAULT 1,
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE RESTRICT,
    UNIQUE KEY uk_college_dept (college_id, name),
    INDEX idx_active (is_active),
    INDEX idx_capacity (remaining_capacity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ======================
-- SAMPLE DATA (optional)
-- ======================
INSERT INTO colleges (name, code, description) VALUES
('College of Engineering', 'ENG', 'Engineering and Technology programs'),
('College of Natural Sciences', 'CNS', 'Science and Mathematics programs'),
('College of Business', 'BUS', 'Business and Economics programs'),
('College of Social Sciences', 'CSS', 'Social Sciences and Humanities');

INSERT INTO departments (college_id, name, code, capacity, remaining_capacity, min_total_score, min_mathematics, min_science, allowed_stream, priority_order) VALUES
(1, 'Computer Science', 'CS', 50, 50, 350, 70, 65, 'Natural Science', 10),
(1, 'Electrical Engineering', 'EE', 40, 40, 340, 75, 70, 'Natural Science', 20),
(1, 'Civil Engineering', 'CE', 45, 45, 320, 65, 60, 'Natural Science', 30),
(2, 'Mathematics', 'MATH', 30, 30, 330, 80, 0, 'Natural Science', 15),
(2, 'Physics', 'PHYS', 25, 25, 340, 70, 75, 'Natural Science', 25),
(2, 'Biology', 'BIO', 35, 35, 300, 50, 70, 'Natural Science', 40),
(3, 'Accounting', 'ACC', 60, 60, 280, 55, 0, NULL, 50),
(3, 'Management', 'MGT', 55, 55, 270, 50, 0, NULL, 55),
(4, 'Economics', 'ECON', 40, 40, 290, 60, 0, 'Social Science', 45),
(4, 'Psychology', 'PSY', 30, 30, 280, 0, 0, 'Social Science', 60);

-- ======================
-- SYSTEM SETTINGS / SELECTION PERIOD
-- ======================
CREATE TABLE system_settings (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    setting_key         VARCHAR(100) UNIQUE NOT NULL,
    setting_value       TEXT,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO system_settings (setting_key, setting_value) VALUES
('selection_open', '1'),
('max_choices', '3'),
('assignment_done', '0'),
('selection_message', 'Selection is currently open. Please submit your department preferences.');

-- ======================
-- STUDENT DEPARTMENT CHOICES (Preferences)
-- ======================
CREATE TABLE student_choices (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id             INT UNSIGNED NOT NULL,
    department_id       INT UNSIGNED NOT NULL,
    choice_order        TINYINT UNSIGNED NOT NULL,   -- 1 = first choice, 2 = second, etc.
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    UNIQUE KEY uk_user_choice (user_id, choice_order),
    UNIQUE KEY uk_user_dept (user_id, department_id),
    INDEX idx_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ======================
-- ASSIGNMENT RESULTS
-- ======================
CREATE TABLE assignments (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id             INT UNSIGNED NOT NULL UNIQUE,
    department_id       INT UNSIGNED,                 -- NULL if not assigned
    choice_order        TINYINT UNSIGNED,             -- which preference was used
    status              ENUM('Assigned', 'Not Assigned', 'Pending') DEFAULT 'Pending',
    score_used          DECIMAL(8,2),
    remarks             TEXT,
    assigned_at         TIMESTAMP NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    INDEX idx_status (status),
    INDEX idx_dept (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
